server:
  port: 8082

spring:
  application:
    name: course-center
  datasource:
    url: jdbc:mysql://rm-bp13q0jl95pd4zo279o.mysql.rds.aliyuncs.com:3306/course
    hikari:
      username: wzw
      password: cM8E!c_89iz2LKV
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

